# **List**

## **Introduction to list and built-in functions**

In [69]:
# list
A=[3,2.5,4.0,-1,5,0]
print(A)
print(type(A)) # type() is a built-in function, prints the type of class of the data
print(len(A))  # len() is a built-in function, prints the length of the data class i.e. number of elements
print(sum(A)) # sum() is a built-in function, makes sum of all the elements of the list

A.append(6)  # append() is a built-in function, appends extra element one at a time
print(A)
print(len(A))
print(sum(A))

A.append((4,6)) # can append a tuple
print(A)
print(len(A))

A.append({4,6}) # can append a set
print(A)
print(len(A))

A.append([4,6])  # can append list
print(A)

A.append('str') # can append string
print(A)

[3, 2.5, 4.0, -1, 5, 0]
<class 'list'>
6
13.5
[3, 2.5, 4.0, -1, 5, 0, 6]
7
19.5
[3, 2.5, 4.0, -1, 5, 0, 6, (4, 6)]
8
[3, 2.5, 4.0, -1, 5, 0, 6, (4, 6), {4, 6}]
9
[3, 2.5, 4.0, -1, 5, 0, 6, (4, 6), {4, 6}, [4, 6]]
[3, 2.5, 4.0, -1, 5, 0, 6, (4, 6), {4, 6}, [4, 6], 'str']


## **Set to list**

In [2]:
a={'string',5,8,3.2,}
print(type(a)) # a is a set
print(len(a))
print(list(a)) # list() is a built-in function that transforms set to list

<class 'set'>
4
[8, 3.2, 5, 'string']


## **Dictionary to list**

In [3]:
b={'x':1,'y':5}
print(type(b)) # b is a dictionary
print(len(b))
print(b)
print(b['y'])
print(list(b)) # list() is a built-in function that transforms dictionary to list

<class 'dict'>
2
{'x': 1, 'y': 5}
5
['x', 'y']


## **Some built-in functions**

In [4]:
A=[3,2.5,4.0,-1,5,0]
print(max(A))           # gives the maximum number
print(min(A))           # gives the minimum number
print(sum(A)/len(A))    # mean of the elements
print(sorted(A))        # sorted in ascending order
print(sorted(A, reverse=True))   # sorted in descending order
print(A)                         # Original A remains unchanged

5
-1
2.25
[-1, 0, 2.5, 3, 4.0, 5]
[5, 4.0, 3, 2.5, 0, -1]
[3, 2.5, 4.0, -1, 5, 0]


In [6]:
B=['Sima','Zakir','Alex','sima','Mita']   # alpahabetically sorted

print(sorted(B))

print(sorted(B, reverse=True))

['Alex', 'Mita', 'Sima', 'Zakir', 'sima']
['sima', 'Zakir', 'Sima', 'Mita', 'Alex']


In [9]:
C=['236','-105','925','1000', 'Sima','Zakir','Alex','sima','Mita']  # minus sign comes first then ascending order of 1st and 2nd digits and so on

print(sorted(C))  # sorts the strings of numbers first and then strings of alphabets

print(sorted(C, reverse=True))

['-105', '1000', '236', '925', 'Alex', 'Mita', 'Sima', 'Zakir', 'sima']
['sima', 'Zakir', 'Sima', 'Mita', 'Alex', '925', '236', '1000', '-105']


**The built-in function _enumerate(list/string etc, start=n)_ iterates index and the corresponding object.**

In [211]:
A=[3,2.5,4.0,-1,5,0]
en_A=enumerate(A) # Default start=0
print(en_A)
for i in en_A:
    print(i)

(0, 3)
(1, 2.5)
(2, 4.0)
(3, -1)
(4, 5)
(5, 0)


In [13]:
A=[3,2.5,4.0,-1,5,0]
en_A=enumerate(A, start=-1) 
             # start from customized index -1 (corresponding to the first object of the list, left to right)
print(en_A)
print(type(en_A))
print(list(en_A))

<class 'enumerate'>
[(-1, 3), (0, 2.5), (1, 4.0), (2, -1), (3, 5), (4, 0)]
set()


## **Indexing**

**List is ordered and so each element of tuple has a definite positional index.** <br>
Left to right indexing is 0 to (n-1) and right to left indexing is -1 to -n. Where n is the number of elements in the list (length of the list).

In [508]:
A=[3,2.5,4.0,-1,5,0]
print(len(A))
print(A[0])
print(A[5])
print(A[-6])
print(A[-1])

6
3
0
3
0


## **Slicing the list**

Positive step size represents the slicing direction left to right and negative step size represents the slicing direction right to left. If the direction represented by the journey start to stop and the direction represented by the sign of the step conflict, then slicing not possible resulting in list with no elements.

In [8]:
A=[3, 2.5, 4.0, -1, 5, 0]
print(A[1:4:1]) # upto index 3 (left to right)
print(A[1:4])   # Default step size is 1
print(A[:4])    # Default start is 0 (left to right) and default step size 1
print(A[2:])    # Default stop is n-1 (left to right) and default step size 1. n is the length of the list
print(A[-3:])   # Default stop is -n (slicing left to right) and default step size 1.
print(A[-5:5])  # Start at -5 and stop at 5-1=4 (slicing left to right) and default step size 1.
print(A[-3::-1]) # Slicing right to left as step size is negative which reverses the direction of slicing
print(A[-3:-7:-1])
print(A[-5:5:-1]) # slicing not possible. Directional conflicts
print(A[5:-5:-1])
print(A[6:2:-1])
print(A[6:2:1])   # slicing not possible. Directional conflicts
print(A[-2:2:1])  # slicing not possible. Directional conflicts
print(A[-2:2:-1])

[2.5, 4.0, -1]
[2.5, 4.0, -1]
[3, 2.5, 4.0, -1]
[4.0, -1, 5, 0]
[-1, 5, 0]
[2.5, 4.0, -1, 5]
[-1, 4.0, 2.5, 3]
[-1, 4.0, 2.5, 3]
[]
[0, 5, -1, 4.0]
[0, 5, -1]
[]
[]
[5, -1]


## **List Methods**

Methods are some specific functions designed to apply on object

### **# Check the Directory for the methods of list**

In [9]:
print(dir(list))

['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [10]:
#print(help(list.__add__))
a=[1,2]
b=[3,4]
print(a.__add__(b))

[1, 2, 3, 4]


In [11]:
#print(help(list.__class__))
a=[1,2]
print(a.__class__)

<class 'list'>


In [12]:
#print(help(list.__contains__))
a=[1,2]
print(a.__contains__(2))
print(a.__contains__(3))

True
False


In [13]:
print(help(list.__delattr__))

Help on wrapper_descriptor:

__delattr__(self, name, /)
    Implement delattr(self, name).

None


In [14]:
#print(help(list.__delitem__))
c=[5,3,9,7]
c.__delitem__(2)
print(c)

[5, 3, 7]


In [16]:
#print(help(list.__sizeof__)) # Return the size of the list in memory, in bytes.
A=[3, 2.5, 4.0, -1, 5, 0]

print(A.__sizeof__())

88


### **# First index location of element of the list**

In [15]:
#print(help(list.index))
A=[3, 2.5, 4.0, -1, 5, 0, 2.5]
print(A.index(2.5))         # Finds the first index location of the element 2.5 in A
# or
print(list.index(A,2.5))


B=['Sima','Zakir','Alex','Mita']
print(B.index('Mita'))      # Finds the index location of the element 'Mita' in B
# or
print(list.index(B, 'Mita'))

1
1
3
3


In [16]:
X=[3, 2.5, 4.0, -1, 5, 0, 4.0, -1]
print(X.index(max(X)))    # Finds the first index location of the maximum element in A
print(X.index(min(X)))    # Finds the first index location of the minimum element in A

4
3


### **# Reverse the list in place**

In [17]:
#print(help(list.reverse))
A=[3, 2.5, 4.0, -1, 5, 0, 2.5]
A.reverse()
print(A)      # Original list gets reversed

[2.5, 0, 5, -1, 4.0, 2.5, 3]


### **# Sorting**

The built-in function **_sorted(list)_** returns a sorted list and leaves the original list unchanged. But the list method **_sort()_** return no new list but alter the original list.

In [58]:
#print(help(list.sort))
A=[3, 2.5, 4.0, -1, 5, 0, 2.5]
A.sort()                                # Sort in ascending order
print(A)

A.sort(reverse=True)                    # Sort in descending order
print(A)

B=['Sima','Zakir','Alex','Mita']
B.sort()
print(B)

C=['236','-105','925','1000']
C.sort()
print(C)

[-1, 0, 2.5, 2.5, 3, 4.0, 5]
[5, 4.0, 3, 2.5, 2.5, 0, -1]
['Alex', 'Mita', 'Sima', 'Zakir']
['-105', '1000', '236', '925']


In [67]:
A=[[5,9],[48,2],[35,70]]

def f(x):
    return x[0]
A.sort(key=f)    # sorting with respect to the first element of lists of the list A
print(A)

def g(x):
    return x[1] 
A.sort(key=g)   # sorting with respect to the second element of lists of the list A
print(A)

#list(A.index(j) for j in A)

[[5, 9], [35, 70], [48, 2]]
[[48, 2], [5, 9], [35, 70]]


### **# Append object to the end of the list**

Returns new list changing the original one.

In [70]:
#print(help(list.append))
A=[3,2.5,4.0,-1,5,0]
A.append(6)        
print(A)             

A.append((4,6)) # can append a tuple
print(A)
print(len(A))

A.append({4,6}) # can append a set
print(A)
print(len(A))

A.append([4,6])  # can append list
print(A)

A.append('str') # can append string
print(A)

[3, 2.5, 4.0, -1, 5, 0, 6]
[3, 2.5, 4.0, -1, 5, 0, 6, (4, 6)]
8
[3, 2.5, 4.0, -1, 5, 0, 6, (4, 6), {4, 6}]
9
[3, 2.5, 4.0, -1, 5, 0, 6, (4, 6), {4, 6}, [4, 6]]
[3, 2.5, 4.0, -1, 5, 0, 6, (4, 6), {4, 6}, [4, 6], 'str']


In [20]:
# Fibonacci Sequence using append()
F=[0,1]
n=eval(input('Enter the number of elements you want in the sequence'))
for i in range(n-2):
    F.append(F[-2]+F[-1])
print(F)
m=eval(input('Enter the position of the number which you want to see (starting from 1st)'))
print(F[m-1])

Enter the number of elements you want in the sequence 12


[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


Enter the position of the number which you want to see (starting from 1st) 12


89


### **# Insert object before index.**

#### ## **_.insert(index position, object)_**, object can be number, string, list, tuple, set etc.

**_A.insert(x,y)_** inserts y before xth index position in the original list A. After the operation the original list gets changed and in the new list the index position of the new object y becomes x.

In [21]:
#print(help(list.insert))
A=[3, 2.5, 4.0, -1, 5, 0, 2.5]
A.insert(2,3)               
print(A)

[3, 2.5, 3, 4.0, -1, 5, 0, 2.5]


In [22]:
A=[3, 2.5, 4.0, -1, 5, 0, 2.5]
A.insert(2,[5,9])
print(A)

[3, 2.5, [5, 9], 4.0, -1, 5, 0, 2.5]


In [23]:
A=[3, 2.5, 4.0, -1, 5, 0, 2.5]
A.insert(2,'str')
print(A)

[3, 2.5, 'str', 4.0, -1, 5, 0, 2.5]


### **# Remove and return item at index (default last)**

#### **_.pop(index position of the object)_**. Can remove only one object at a time

In [24]:
#print(help(list.pop))
A=[3, 2.5, 4.0, -1, 5, 0, 2.5]
A.pop()
print(A)
A.pop()
print(A)

[3, 2.5, 4.0, -1, 5, 0]
[3, 2.5, 4.0, -1, 5]


In [25]:
A=[3, 2.5, 4.0, -1, 5, 0, 2.5]
A.pop(1)
print(A)
A.pop(-1)
print(A)

B=['Sima','Zakir','Alex','Mita']
B.pop(2)
print(B)

[3, 4.0, -1, 5, 0, 2.5]
[3, 4.0, -1, 5, 0]
['Sima', 'Zakir', 'Mita']


#### **List as stack with combination of _.append()_ and _.pop()_**

In [150]:
A=[3, 2.5, 4.0, -1, 5, 0, 2.5]
print(len(A))
n=eval(input('Enter the value'))
A.append(n)          # Object enters at the end
A.pop(0)             # And object gets removed from begining. 
print(A)             # Combination of .append() and .pop() makes the list a stack.
print(len(A))

7


Enter the value 12


[2.5, 4.0, -1, 5, 0, 2.5, 12]
7


### **# Remove first occurrence of object**

#### **_.remove(object)_**. Notice **_.pop()_** vs **_.remove()_**.

In [1]:
#print(help(list.remove))
A=[3, 2.5, 4.0, -1, 5, 0, 2.5, 4.0]
A.remove(4.0)
print(A)

B=['Sima','Zakir','Alex','Mita']
B.remove('Alex')
print(B)

[3, 2.5, -1, 5, 0, 2.5, 4.0]
['Sima', 'Zakir', 'Mita']


### **# Delete a segment**

**_del_** is a built-in function but not a list method.

In [38]:
A=[3, 2.5, 4.0, -1, 5, 0, 2.5]
del A[1:3]                       # Delete the sliced elements.
print(A)                         # Original list gets altered.

[3, -1, 5, 0, 2.5]


In [154]:
A=[3, 2.5, 4.0, -1, 5, 0, 2.5]
del A[:]                       # Delete the sliced elements.
print(A) 

[]


In [153]:
A=[3, 2.5, 4.0, -1, 5, 0, 2.5]
del A                       # Can delete the entire list (or other variables)
print(A) 

NameError: name 'A' is not defined

### **# Replace an item**

In [40]:
A=[3, 2.5, 4.0, -1, 5, 0, 2.5]
A[3]=10                        # The item at position 3 is replaced by 10.
print(A)                       # Original list gets altered.

[3, 2.5, 4.0, 10, 5, 0, 2.5]


### **# Return number of occurrences of item.**

In [139]:
#print(help(list.count))
X=[3, 2.5, 4.0, -1, 5, 0, 4.0, -1]
print(X.count(4.0))
print(X.count(X[2]))
print(X.count(6))

2
2
0


### **# Return a shallow copy of the list.**

In [52]:
#print(help(list.copy))
A=[3, 2.5, 4.0, -1, 5, 0, 2.5]
B=A.copy()
print(B)

[3, 2.5, 4.0, -1, 5, 0, 2.5]


### **# Remove all items from list.**

In [58]:
#print(help(list.clear))
A=[3, 2.5, 4.0, -1, 5, 0, 2.5]
print(A.clear())

None


### **# Extend list by appending elements from the iterable.**

Append more than one item at the end of the list.

In [65]:
#print(help(list.extend))
A=[3, 2.5, 4.0, -1, 5, 0, 2.5]
A.extend(i for i in range(4))
print(A)                            # Original list gets altered.

[3, 2.5, 4.0, -1, 5, 0, 2.5, 0, 1, 2, 3]


### **# Concatenation of lists.**

The operator **+** concatenates the lists. **_integer*list_** means the list gets concatenated integer times.

In [67]:
A=[3, 2.5, 4.0, -1, 5, 0, 2.5]
B=['Sima','Zakir','Alex','Mita']

print(A+B)

x=[2,3,5]
y=['a','b']

print(3*x+2*y)

[3, 2.5, 4.0, -1, 5, 0, 2.5, 'Sima', 'Zakir', 'Alex', 'Mita']
[2, 3, 5, 2, 3, 5, 2, 3, 5, 'a', 'b', 'a', 'b']


## **List Comprehension**

### **# Create a list of the squares of the numbers of a given list**

In [76]:
x=[1,2,3,4,5]
y=[i**2 for i in x]   # list comprehension
print(y)

# vs

x=[1,2,3,4,5]
y=[]
for i in x:           # for loop
    y.append(i**2)
print(y)

[1, 4, 9, 16, 25]
[1, 4, 9, 16, 25]


### **# From a list of positive and negatives, create a list of absolute values of all the numbers**

In [214]:
x=[-1,2,-3,-4]
y=[abs(i) for i in x]
print(y)

[1, 2, 3, 4]


### **# Separate out positive numbers**

In [93]:
x=[-1,0,1,2,-3,5,-6]
y=[i for i in x if i>0]        # With logical if
print(y)

#vs

z=[]
for i in x:
    if i>0:
        z.append(i)
print(z)

[1, 2, 5]
[1, 2, 5]


### **# Separate out even or odd numbers**

In [70]:
L=[2,9,12,23,46,78,45,94]
e=[i for i in L if i%2==0]     # List comprehension with logical if
print(e)                       # even numbers

# vs

E=[]
for i in L:                    # for loop
    if i%2==0:
        E.append(i)
print(E)


o=[i for i in L if i%2==1]     # List comprehension with logical if
print(o)                       # odd numbers

#vs

O=[]
for i in L:                    # for loop
    if i%2==1:
        O.append(i)
print(O)

[2, 12, 46, 78, 94]
[2, 12, 46, 78, 94]
[9, 23, 45]
[9, 23, 45]


### **# Addition of each elements of one list to the each elements of other list**

In [88]:
a=[2, 12, 46, 78, 94]
b=[9, 23, 45]
print([i+j for i in a for j in b]) # one by one take element from 'a' and add with each elemnts of the 'b'
# vs
print([i+j for j in b for i in a]) # one by one take element from 'b' and add with each elemnts of the 'a'
print([i+j for i in a for j in b if (i-j)%3==0])

[11, 25, 47, 21, 35, 57, 55, 69, 91, 87, 101, 123, 103, 117, 139]
[11, 21, 55, 87, 103, 25, 35, 69, 101, 117, 47, 57, 91, 123, 139]
[25, 21, 57, 87, 123]


### **# Making pairs of the elements taken from two different lists**

In [93]:
print([[i,j] for i in a for j in b]) # list of lists of pair
# vs
print([[i,j] for j in b for i in a])

print([(i,j) for i in a for j in b]) # list of tuples of pair
# vs
print([(i,j) for j in b for i in a])

[[2, 9], [2, 23], [2, 45], [12, 9], [12, 23], [12, 45], [46, 9], [46, 23], [46, 45], [78, 9], [78, 23], [78, 45], [94, 9], [94, 23], [94, 45]]
[[2, 9], [12, 9], [46, 9], [78, 9], [94, 9], [2, 23], [12, 23], [46, 23], [78, 23], [94, 23], [2, 45], [12, 45], [46, 45], [78, 45], [94, 45]]
[(2, 9), (2, 23), (2, 45), (12, 9), (12, 23), (12, 45), (46, 9), (46, 23), (46, 45), (78, 9), (78, 23), (78, 45), (94, 9), (94, 23), (94, 45)]
[(2, 9), (12, 9), (46, 9), (78, 9), (94, 9), (2, 23), (12, 23), (46, 23), (78, 23), (94, 23), (2, 45), (12, 45), (46, 45), (78, 45), (94, 45)]


In [104]:
from math import pi, sin
theta=[i*pi/2 for i in range(6)]    # theta in radian
print(theta)

sin_theta=[sin(j) for j in theta]
print(sin_theta)

[0.0, 1.5707963267948966, 3.141592653589793, 4.71238898038469, 6.283185307179586, 7.853981633974483]
[0.0, 1.0, 1.2246467991473532e-16, -1.0, -2.4492935982947064e-16, 1.0]


## **Nested List**

#### **Nested list is the list of lists.** 

In [145]:
N=[[1,2,3],[4,5],[6,7,8,9]]  # N is a nested list
print(len(N))
print(N[0])
print(N[1])
print(N[2])
print(N[0][1])

M=[[1,2,3],[4,5,6]]          # M is a nested list
print(M)
print(M[0][1])
import numpy as np
print(np.array(M))           # Nested list having equal lengths for all the elemntary lists, 
                             # can be converted into numpy array.
print(np.array(M)[0,1])
print(np.array(N))           # Nested list M vs N

3
[1, 2, 3]
[4, 5]
[6, 7, 8, 9]
2
[[1, 2, 3], [4, 5, 6]]
2
[[1 2 3]
 [4 5 6]]
2
[list([1, 2, 3]) list([4, 5]) list([6, 7, 8, 9])]


/opt/intel/oneapi/intelpython/latest/lib/python3.7/site-packages/ipykernel_launcher.py:15: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  from ipykernel import kernelapp as app


# **Sring**

**Anything inside single quotes or double quotes. Any input that the computer takes through the _input()_ function is a _string_.**

## **Introduction to string and some built-in functions.**

In [240]:
a='3.14'
b='Sampad Mandal'
c=" @A58%c"
print(type(a))
print(type(b))
print(type(c))   # type() is a buit-in function

print(len(b))    # space is also an element in the string.


print(eval(a))    # the buit-in function eval() can evaluate the string of digits or string of sum of digits.
d='19 + 10'
print(eval(d))


e='1234'
print(int(e))     # buit-in function int() returns the string of integer (not float) as integer.

print(float(e))   # buit-in function float() returns the string of integer or float as float.
print(float(a))

# But 

print(int(3.14))  # converts the floating point number to integer one.
# or
print(int(eval(a))) # because eval() converts a='3.14' string to 3.14 floating point number.
# or
print(int(float(a))) # because float() converts a='3.14' string to 3.14 floating point number.
print(type(int(float(a))))


<class 'str'>
<class 'str'>
<class 'str'>
13
3.14
29
1234
1234.0
3.14
3
3
3
<class 'int'>


In [239]:
n=132
print(str(n))  # built function str() makes the number string
print(type(str(n)))
str(n)           

132
<class 'str'>


'132'

In [238]:
l=[1,3,2]
L=str([1,3,2]) # built function str() makes the list string
print(L)
print(type(L))
L

[1, 3, 2]
<class 'str'>


'[1, 3, 2]'

**The built-in function _enumerate(list/string etc, start=n)_ iterates index and the corresponding object.**

In [218]:
s='Sampad 19@'
s_en=enumerate(s) # Default start=0
print(s_en)
for i in s_en:
    print(i)

(0, 'S')
(1, 'a')
(2, 'm')
(3, 'p')
(4, 'a')
(5, 'd')
(6, ' ')
(7, '1')
(8, '9')
(9, '@')


In [220]:
s='Sampad 19@'
s_en=enumerate(s, start=-2) 
                  # Start from the customized index number -2 corresponding to the 1st object, left to right
print(s_en)
for i in s_en:
    print(i)

(-2, 'S')
(-1, 'a')
(0, 'm')
(1, 'p')
(2, 'a')
(3, 'd')
(4, ' ')
(5, '1')
(6, '9')
(7, '@')


## **Iteration over a string**

In [206]:
for i in 'abc123':
    print(i)
#    print(i, end = '')

a
b
c
1
2
3


## **Indexing**

In [241]:
w='Python'
print(w[0])  
print(type(w[0]))
w[0]          # see the difference

P
<class 'str'>


'P'

## **Slicing**

In [242]:
# Slicing
print(w[-1:-4:-2])
print(w[::-1])    # just reversing the string
print(type(w[::-1]))
w[::-1]
#w[-1:-4:-2]

nh
nohtyP
<class 'str'>


'nohtyP'

**Checking a sequence (string or number) _palindrome_ or not.**

In [231]:
n=input('Enter a number') # Do not use eval() function before input() because n has to be a string.
if n==n[::-1]:
    print(eval(n),'is Palindrome')
else:
    print(eval(n), 'is not Palindrome')
n

Enter a number 12321


12321 is Palindrome


'12321'

In [237]:
w=input('Enter a string') # 
if w==w[::-1]:
    print(w,'is Palindrome')
else:
    print(w, 'is not Palindrome')
w

Enter a string p o p


p o p is Palindrome


'p o p'

**String is ordered but unlike list, it is _immutable_**

In [243]:
w[0]='C'

TypeError: 'str' object does not support item assignment

## **Concatenation**

In [246]:
s='abc123'
print(s+s+s)
print(type(s+s+s))
s+s+s

abc123abc123abc123
<class 'str'>


'abc123abc123abc123'

In [249]:
s='R'
print(3*s)
print(type(3*s))
3*s

RRR
<class 'str'>


'RRR'

In [251]:
s1='Sampad'
s2=' '
s3='Mandal'
print(s1+s2+s3)
s1+s2+s3

Sampad Mandal


'Sampad Mandal'

**concatenation and evaluation**

In [258]:
eval('123'+'456') # 1st concatenate '123' & '456' and then evaluate the value of the concatenated string

123456

In [259]:
eval('12.3')+eval('45.6') # 1st evaluate the individual strings to digits and then operate the sum

57.900000000000006

In [256]:
eval('12.3+45.6') # 1st evaluate the string to digit and then operate the sum

57.900000000000006

## **Methods on String**

### **# Check the Directory for the methods of string**

In [261]:
print(dir(str))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']


In [ ]:
print(help(str.capitalize))

### **# Capitalization**

**Make the first character(any albhabet) have upper case and the rest lower. If the 1st caharacter is a digit any symbol having no upper case then it's remain unchanged.**

In [269]:
#print(help(str.capitalize))
s='abc123'
print(s.capitalize())
s.capitalize()

Abc123


'Abc123'

In [273]:
s='γ23abc' # γ is typed by Ctrl+Shift+u and then 03b3 and then Sheft+Enter
print(s.capitalize())
s.capitalize()

Γ23abc


'Γ23abc'

In [275]:
s='123abc'
print(s.capitalize())
s.capitalize()

123abc


'123abc'

In [281]:
s='@23abc'
print(s.capitalize())
s.capitalize()

@23abc


'@23abc'

In [279]:
s='α23abc' # α is typed by Ctrl+Shift+u and then 03b1 and then Sheft+Enter
print(s.capitalize()) # upper case of both α and a is A
s.capitalize()

Α23abc


'Α23abc'

In [505]:
s='tHis is thE fiRST liNe'
print(s.capitalize()) 
s.capitalize()

This is the first line


'This is the first line'

### **# Converting the string to lowercase for which it is possible**

In [499]:
#print(help(str.lower))
s='Abc123#A'
print(s.lower())
s.lower()

abc123#a


'abc123#a'

### **# Return True if the string is a lowercase string i.e., all cased characters in the string are lowercase, False otherwise.**

In [5]:
#print(help(str.islower))
s1='abc123#A'
print(s1.islower())
s2='abc123#a'
print(s2.islower())

False
True


### **# Converting the string to uppercase for which it is possible**

In [492]:
#print(help(str.upper))
s='Abc123#α'
print(s.upper())   
s.upper()

ABC123#Α


'ABC123#Α'

### **#  Return True if the string is an uppercase string i.e., all cased characters in the string are uppercase, False otherwise.**

In [140]:
#print(help(str.isupper))
s1='abc123#A'
print(s1.isupper())
print(s1[-1].isupper())
s2='ABC123#A'
print(s2.isupper())

False
True
True


### **# Converting the string to titlecase i.e. each word starts with uppercase and the rest lower**

In [504]:
#print(help(str.title))
s='tHis is thE fiRST liNe'
print(s.title()) 
s.title()

This Is The First Line


'This Is The First Line'

### **# Return True if the string is a title-cased string, False otherwise.**

In [17]:
#print(help(str.istitle))
s1='tHis is thE fiRST liNe'
print(s1.istitle()) 
s2='This Is The First Line'
print(s2.istitle()) 

False
True


### **# Return a copy of the string with leading and trailing whitespace removed.**

In [33]:
#print(help(str.strip))
s=' This Is The First Line  '
print(s.strip()) 
s.strip()          # removes the leading and trailing whitespaces

This Is The First Line


'This Is The First Line'

### **#   Return a copy of the string with leading whitespace removed.**

In [39]:
#print(help(str.lstrip))
s=' This Is The First Line  '
print(s.lstrip()) 
s.lstrip()        # removes only the leading whitespaces

This Is The First Line  


'This Is The First Line  '

### **# Return a copy of the string with trailing whitespace removed.**

In [42]:
#print(help(str.rstrip))
s=' This Is The First Line  '
print(s.rstrip()) 
s.rstrip()        # removes only the trailing whitespaces

 This Is The First Line


' This Is The First Line'

### **# Return True if the string is a whitespace string, False otherwise.**

In [98]:
print(help(str.isspace))
s=' This Is The First Line  '
print(s.isspace())
s2='s a m p a d'
print(s2.isspace())

Help on method_descriptor:

isspace(self, /)
    Return True if the string is a whitespace string, False otherwise.
    
    A string is whitespace if all characters in the string are whitespace and there
    is at least one character in the string.

None
False
False


### **# Return a list of the words in the string, using sep as the delimiter string.**

**_.split('separator',maxsplit=number of splitting attempts starting from left to right)_, default separator is whitespace and default maxsplit is the maximum numbers of splitting possible with respect to the separator.** 

In [14]:
#print(help(str.split))
s=' This Is The First     Line  '
print(s.split())
print(s.split(maxsplit=2)) 
print(s.split(maxsplit=4)) 
print(s.split(maxsplit=5))

s2=' ,This, Is, The, First, Line,  '
print(s2.split(sep=','))
print(s2.split(',',5))
print(s2.split(',',maxsplit=6))

['This', 'Is', 'The', 'First', 'Line']
['This', 'Is', 'The First     Line  ']
['This', 'Is', 'The', 'First', 'Line  ']
['This', 'Is', 'The', 'First', 'Line']
[' ', 'This', ' Is', ' The', ' First', ' Line', '  ']
[' ', 'This', ' Is', ' The', ' First', ' Line,  ']
[' ', 'This', ' Is', ' The', ' First', ' Line', '  ']


**_.rsplit('separator',maxsplit=number of splitting attempts starting from right to left)_, default separator is whitespace and default maxsplit is the maximum numbers of splitting possible with respect to the separator.** 

In [132]:
#print(help(str.rsplit))
s=' This Is The First     Line  '
print(s.rsplit())
print(s.rsplit(maxsplit=2)) 
print(s.rsplit(maxsplit=4)) 
print(s.rsplit(maxsplit=5))

s2=' ,This, Is, The, First, Line,  '
print(s2.rsplit(sep=','))
print(s2.rsplit(',',5))
print(s2.rsplit(',',maxsplit=6))

['This', 'Is', 'The', 'First', 'Line']
[' This Is The', 'First', 'Line']
[' This', 'Is', 'The', 'First', 'Line']
['This', 'Is', 'The', 'First', 'Line']
[' ', 'This', ' Is', ' The', ' First', ' Line', '  ']
[' ,This', ' Is', ' The', ' First', ' Line', '  ']
[' ', 'This', ' Is', ' The', ' First', ' Line', '  ']


In [136]:
print(help(str.splitlines))
s='My name is Sampad. I am currently pursuing my Ph.D. in Comp. Mat. Science.\
 My area of interest is the searching for efficient thermoelectric materials.'
print(s.splitlines(True))

Help on method_descriptor:

splitlines(self, /, keepends=False)
    Return a list of the lines in the string, breaking at line boundaries.
    
    Line breaks are not included in the resulting list unless keepends is given and
    true.

None
['My name is Sampad. I am currently pursuing my Ph.D. in Comp. Mat. Science. My area of interest is the searching for efficient thermoelectric materials.']


In [12]:
print(help(str.join))

Help on method_descriptor:

join(self, iterable, /)
    Concatenate any number of strings.
    
    The string whose method is called is inserted in between each given string.
    The result is returned as a new string.
    
    Example: '.'.join(['ab', 'pq', 'rs']) -> 'ab.pq.rs'

None


In [11]:
print(help(str.ljust))

Help on method_descriptor:

ljust(self, width, fillchar=' ', /)
    Return a left-justified string of length width.
    
    Padding is done using the specified fill character (default is a space).

None


### **# Counting**

**_.count('substring', start_index_position_of_counting, stop_index_position_of_counting)_. Return the number of non-overlapping occurrences of substring**

In [374]:
#print(help(str.count))
s='The Beautiful Mind'
print(s.count('T'))
print(s.count('i'))  # Default start at s[0]='T' and default stop s[18] i.e takes upto 'd' of the word 'Mind'
print(s.count('i',4,13)) # Stop=s[13] i.e. takes upto s[12]='l' of 'Beautiful' start=s[4]='B' of 'Beautiful'
print(s.count('in'))
print(s.count('ful'))

1
2
1
1
1


### **# Encoding String**

In [332]:
#print(help(str.encode))
s='The Beautiful Mind'
print(s.encode())

b'The Beautiful Mind'


### **# Checking whether the string starts with the specified prefix or not**

**_.startswith('prefix', start_index_position_of_counting, stop_index_position_of_counting)_. Prefix may be any substring. Returns in boolean**

In [138]:
#print(help(str.startswith))
s='The Beautiful Mind'
print(s.startswith('T')) # Default start at s[0]='T' and default stop s[18] i.e takes upto 'd' of the word 'Mind'


True


### **# Checking whether the string ends with the specified suffix or not**

**_.endswith('suffix', start_index_position_of_counting, stop_index_position_of_counting)_. Suffix may be any substring. Returns in boolean**

In [494]:
#print(help(str.endswith))
s='The Beautiful Mind'
print(s.endswith('d')) # Default start at s[0]='T' and default stop s[18] i.e takes upto 'd' of the word 'Mind'
print(s.endswith('d',0,17)) # Stop s[17] i.e. takes upto 'n' of the word 'Mind' starting from s[0]='T' of 'The'
print(s.endswith('l',0,13)) # Stop=s[13] i.e. takes upto s[12]='l' of 'Beautiful' 
print(s.endswith('l',4,13)) # Start=s[4]='B' of the word 'Beautiful'
print(s.endswith('ll',4,13)) # Start=s[4]='B' of the word 'Beautiful'
print(s.endswith('ful',4,13))

True
False
True
True
False
True


### **# Expanding the tab caharcters using spaces in a copy of the string**

**_.expandtabs(integer)_, where integeris the tab size. Default tab size is the space of 8 characters. Original string remains unaltered**

In [361]:
#print(help(str.expandtabs))
s='Sampad\tMandal' # '\t' is the tab character
print(s.expandtabs())  # Default tab size is the space of 8 characters.
print(s.expandtabs(16)) # Tab size is the space of 16 characters.
print(s)                # Original string remains unaltered
s.expandtabs(16)

Sampad  Mandal
Sampad          Mandal
Sampad	Mandal


'Sampad          Mandal'

### **# Finding the lowest index in string where substring is found**

**_.find('substring', start_index_position_of_counting, stop_index_position_of_counting)_ and <br> _.index('substring', start_index_position_of_counting, stop_index_position_of_counting)_**

In [396]:
#print(help(str.find))
s='The Beautiful Mind'
print(s.find('d'))
print(s.find('i')) # 1st 'i' between default start=s[0]='T' and s[17]='d' i.e. default stop=s[18]
print(s.find('ifu'))
print(s.find('i',14)) # 1st 'i' between start=s[14]='M' and s[17]='d' i.e. default stop=s[18]

17
9
9
15


In [564]:
#print(help(str.rfind))
s='The Beautiful Mind'
print(s.rfind('i'))
print(s.rfind('i',14))
print(s.rfind('i',9,14))

15
15
9


In [395]:
#print(help(str.index))
s='The Beautiful Mind'
print(s.index('d'))
print(s.index('i'))
print(s.index('ifu'))
print(s.index('i',14))

17
9
9
15


In [565]:
#print(help(str.rindex))
s='The Beautiful Mind'
print(s.rindex('i'))
print(s.rindex('i',14))
print(s.rindex('i',9,14))

15
15
9


In [403]:
print(help(str.format))
s='The Beautiful Mind'
s.format('{Heart}')

Help on method_descriptor:

format(...)
    S.format(*args, **kwargs) -> str
    
    Return a formatted version of S, using substitutions from args and kwargs.
    The substitutions are identified by braces ('{' and '}').

None


'The Beautiful Mind'

### **# Whether the string is alpha-numeric or not.**

**Presence of any special chrater (like !,@,#,$,%,>,^,&,*,(,_,-,+,=,.,: etc.) which is not alphbet nor numerical value, or space makes the string non-alpha-numeric. String with no element is not a alpha-numeric.**

In [439]:
#print(help(str.isalnum))
s1='γ526s'      # γ is greek albhabet
print(s1.isalnum())
s2='γ526s@'     # @ is a special character
print(s2.isalnum())
s3='sampad'     # All are alphabets
print(s3.isalnum())
s4='sampad.'    # . is a special charater
print(s4.isalnum())
s5='3.14'       # . is a special charater
print(s5.isalnum())
s6='314'        # All are numeriacal
print(s6.isalnum())
s7='αβγ'        # All are greek alphabets 
print(s7.isalnum())
s8='sampad '    # Presence of space makes the string non-alpha-numeric
print(s8.isalnum())
s9=''           # No charater in the string
print(s9.isalnum())

True
False
True
False
False
True
True
False
False


### **# Whether the string is alphabetic or not.**

In [141]:
#print(help(str.isalpha))
s1='γ526s'      
print(s1.isalpha())
s2='γs'         # γ is greek albhabet.
print(s2.isalpha())
s3='γs.'
print(s3.isalpha())
s4=''           # No charater in the string
print(s4.isalpha())

False
True
False
False


### **# Whether the string is numeric or not.**

In [454]:
#print(help(str.isnumeric))
s1='γ526s'      
print(s1.isnumeric())
s2='526'
print(s2.isnumeric())
s3='526.'
print(s3.isnumeric())
s4=''           # No charater in the string
print(s4.isnumeric())

False
True
False
False


### **# Whether the string is ASCII or not.**

In [469]:
#print(help(str.isascii))
s1='γ526s'      
print(s1.isascii())
s2='γs'
print(s2.isascii())
s3='ab'
print(s3.isascii())
s4='ab#. '            # Special charaters and spaces are ASCII too.
print(s4.isascii())   
s5='3.14'             # Numeric are also ASCII
print(s5.isascii())
s6=''                 # No charater is also ASCII
print(s6.isascii())

False
False
True
True
True
True


### **# Whether the string is of all digits or not.**

In [473]:
#print(help(str.isdigit))
s1='3.14'             
print(s1.isdigit())
s2='314'             
print(s2.isdigit())

False
True


### **# Whether the string is decimal or not.**

In [21]:
#print(help(str.isdecimal))
s1='3.0'             
print(s1.isdecimal())
s2='314'             
print(s2.isdecimal())

False
True


# **Operators Other Than Arithmetic Operators**

## **# Logical Operators**

| Operators || Descriptions |
|-----------||--------------|
| and       || True if all statements are true |
| or        || True if any one of the statements is true|
| not       ||Just reveses the result. False if the result is true|                                      |

**Precedence _not > and > or_**

In [521]:
x=6
print(x<5 and x<10) # First statement is false 
print(x>5 and x>10) # Second statement is false
print(x>5 and x<10) # Both statements are true
print(x>5 and x<10 and x<8) # All statements are true

False
False
True
True


In [546]:
x=6
print(not(x<5 and x<10)) # First statement is false 
print(not(x>5 and x>10)) # Second statement is false
print(not(x>5 and x<10)) # Both statements are true
print(not(x>5 and x<10 and x<8)) # All statements are true

True
True
False
False


In [525]:
x=6
print(x<5 or x<10)      # Second statement is true
print(x>5 or x>10)      # First statement is true
print(x>5 or x<10)      # Both statements are true
print(x<5 or x>10)      # Both statements are false
print(x<5 or x<10 or x<4) # Second statement is true
print(x<5 or x>10 or x<4) # # All statements are false

True
True
True
False
True
False


In [547]:
x=6
print(not(x<5 or x<10))      # Second statement is true
print(not(x>5 or x>10))      # First statement is true
print(not(x>5 or x<10))      # Both statements are true
print(not(x<5 or x>10))      # Both statements are false
print(not(x<5 or x<10 or x<4)) # Second statement is true
print(not(x<5 or x>10 or x<4)) # # All statements are false

False
False
False
True
False
True


In [536]:
x=6
print(x>5 or x>10 and x<4)    # Precedence 'and' > 'or'. So 'and' operates first and the 'or'.
print((x>5 or x>10) and x<4)  # Due to parenthesis 'or' operates first and then 'and'.
print(x>5 or x<10 and x<4)    # Precedence 'and' > 'or'. So 'and' operates first and the 'or'.
print((x>5 or x<10) and x<4)  # Due to parenthesis 'or' operates first and then 'and'.

True
False
True
False


In [544]:
x=6
print(x>5 and x>10 or x>4)

True


## **# Comparison Operators**

| Operator || Name |
|----------||------|
| == || equal |
| != || not equal |
| >  || greater than |
| <  || less than |
| >= || greater than or equal to |
| <= || less than or equal to |

In [556]:
x='s'
y=5
print(x==y)
print(x!=y)

False
True


# **# Identity Operators**

| Operators || Descriptions |
|-----------||--------------|
| is        || True if both variable are the same object |
| is not    || True if both variables are not the same object |

In [552]:
x='s'
y=5
print(x is y)
print(x is not y)

False
True


# **List vs Tuple vs Set vs Dictionary in terms of order and mutability**

## **# List**

### **## Order**

In [108]:
L=[1,5,9.5,'str',{1,8},[9,6],(2,0.5),1e2,6.8]
print(L.index(9.5))
print(L.index({1,8}))
print(L.index((2,0.5)))

2
4
6


### **## Mutability**

In [46]:
L=[1,5,9.5,'str',{1,8},[9,6],(2,0.5),1e2,6.8]
print(id(L))
L[6]=(0.2,5)
print(id(L))
print(L)

22736937357952
22736937357952
[1, 5, 9.5, 'str', {8, 1}, [9, 6], (0.2, 5), 100.0, 6.8]


## **# Tuple**

### **## Order**

In [117]:
T=(1,5,9.5,'str',{1,8},[9,6],(2,0.5),1e2,6.8)
print(T.index(9.5))
print(T.index({1,8}))
print(T.index((2,0.5)))

2
4
6


### **## Mutability**

In [119]:
T=(1,5,9.5,'str',{1,8},[9,6],(2,0.5),1e2,6.8)
T[6]=(0.2,5)
print(T)

TypeError: 'tuple' object does not support item assignment

## **# Set**

### **## Order**

In [122]:
O={1,5,9.5,'str',{1,8},[9,6],(2,0.5),1e2,6.8}
print(O.index(9.5))

TypeError: unhashable type: 'set'

## **# Dictionary**

### **## Order**

# **Matrix multiplication**

In [27]:
A=[[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]

print(len(A))

B = [[5, 8, 1, 2],
     [6, 7, 3, 0],
     [4, 5, 9, 1]]

print(len(B))
print(len(B[1]))

C=[[0,0,0,0],
   [0,0,0,0],
   [0,0,0,0]]

# iterating by row of A
for i in range(len(A)):
 
    # iterating by column by B
    for j in range(len(B[1])):
 
        # iterating by rows of B
        for k in range(len(B)):
            C[i][j] += A[i][k] * B[k][j]

            
print(C)
import numpy as np
print(np.array(C))

3
3
4
[[114, 160, 60, 27], [74, 97, 73, 14], [119, 157, 112, 23]]
[[114 160  60  27]
 [ 74  97  73  14]
 [119 157 112  23]]


In [8]:
A = [[12, 7, 3],
     [4, 5, 6],        # 3x3 matrix
     [7, 8, 9]]

# print(len(A))

B = [[5, 8, 1, 2],
     [6, 7, 3, 0],     # 3x4 matrix
     [4, 5, 9, 1]]

# print(len(B))
# print(len(B[1]))

if len(A[0])==len(B):    # for AB (not BA)
    C=[[0 for c in range(len(B[0]))] for r in range(len(A))]   # for AB (not BA)
    
    # iterating by column by B
    for j in range(len(B[1])): 

        # iterating by row of A
        for i in range(len(A)):
 
            # iterating by rows of B
            for k in range(len(B)):
                C[i][j] += A[i][k] * B[k][j]   # for AB (not BA)

            
    print(C)
    import numpy as np
    print(np.array(C))
else:
    print('AB multiplication is not possible')

[[114, 160, 60, 27], [74, 97, 73, 14], [119, 157, 112, 23]]
[[114 160  60  27]
 [ 74  97  73  14]
 [119 157 112  23]]


In [29]:
import numpy as np
A=np.matrix([[12, 7, 3],
             [4, 5, 6],
             [7, 8, 9]])
#print(A)
B=np.matrix([[5, 8, 1, 2],
             [6, 7, 3, 0],
             [4, 5, 9, 1]])

C=A*B
print(C)
print(list(C))

[[114 160  60  27]
 [ 74  97  73  14]
 [119 157 112  23]]
[matrix([[114, 160,  60,  27]]), matrix([[74, 97, 73, 14]]), matrix([[119, 157, 112,  23]])]


# Matrix summation (addition and subtrction)

In [30]:
A=[[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]


D = [[5, 8, 1],
     [6, 7, 3],
     [4, 5, 9]]

S=[[0,0,0],
   [0,0,0],
   [0,0,0]]

for i in range(len(A)):
    for j in range(len(D)):
        S[i][j] += A[i][j]+D[i][j]
        
print(S)
import numpy as np
print(np.array(S))

[[17, 15, 4], [10, 12, 9], [11, 13, 18]]
[[17 15  4]
 [10 12  9]
 [11 13 18]]


In [31]:
A=[[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]


D=[[5, 8, 1],
   [6, 7, 3],
   [4, 5, 9]]

S=[]

for i in range(len(A)):
    for j in range(len(D)):
        S.append(A[i][j]+D[i][j])
        
print(S)
import numpy as np
print(np.array(S))

[17, 15, 4, 10, 12, 9, 11, 13, 18]
[17 15  4 10 12  9 11 13 18]


In [32]:
import numpy as np
A=np.matrix([[12, 7, 3],
             [4, 5, 6],
    [7, 8, 9]])


D=np.matrix([[5, 8, 1],
             [6, 7, 3],
             [4, 5, 9]])

S=A+D
print(S)

[[17 15  4]
 [10 12  9]
 [11 13 18]]
