# Numpy linear algebra

## Use of `@` operator

In [43]:
import numpy as np
import numpy.linalg as la

In [158]:
a = np.arange(1, 5) # 1D array or vector
b = np.arange(2, 6) # 1D array or vector
c = a@b              # vector dot product or inner product

print(a)
print(b)
print(c)

[1 2 3 4]
[2 3 4 5]
40


In [159]:
a = np.arange(1, 5).reshape((2,2)) # 2D array or matrix
b = np.arange(2, 6).reshape((2,2)) # 2D array or matrix
c = a@b                                # matrix product
d = b@a                                # matrix product

print(a, '\n')
print(b, '\n')
print(c, '\n')
print(d, '\n')

[[1 2]
 [3 4]] 

[[2 3]
 [4 5]] 

[[10 13]
 [22 29]] 

[[11 16]
 [19 28]] 



In [180]:
a = np.arange(1, 5).reshape((2,2)) # 2D array or matrix
b = np.arange(2, 4).reshape((2,1)) # 2D array with 2 rows and 1 column or matrix
e = np.arange(2, 4).reshape((1,2)) # 2D array with 1 row and 2 columns or matrix
c = a@b                                 # matrix product
d = e@a                                # matrix product

print(a, '\n')                         # 2D array
print(b, '\n')                         # 2D array
print(c, '\n')                         # 2D array
print(d, '\n')                         # 2D array

[[1 2]
 [3 4]] 

[[2]
 [3]] 

[[ 8]
 [18]] 

[[11 16]] 



In [181]:
a = np.arange(1, 5).reshape((2,2)) # 2D array or matrix
b = np.arange(2, 4)                # 1D array 
c = a@b                                # matrix product with b acting as 2x1 column matrix
d = b@a                                # matrix product with b acting as 1x2 row matrix

print(a, '\n')                    # 2D array
print(b, '\n')                    # 1D array
print(c, '\n')                    # 1D array
print(d, '\n')                    # 1D array 

[[1 2]
 [3 4]] 

[2 3] 

[ 8 18] 

[11 16] 



## Matrix and Vector Products

`dot()` : Dot product of two arrays if both are 1D arrays.

In [24]:
#help(np.dot)

a = [1, 0, 0, 1]
b = [4, 1, 2, 2]

print(np.dot(a, b)) #  Dot product of two 1D arrays (vectors). Returns scallar. 
print(np.dot(np.array(a), np.array(b)))

6
6


In [209]:
#help(np.dot)

a = [1, 1]              # 1D
b = [[4, 1], [2, 2]]    # 2D


print(b, '\n')            # 2D
print(np.array(b), '\n')  # 2D

#  matrix product between 1D and 2D array
print(np.dot(a, b), '\n')                      # a (1D array) is treated as row vector # gives 1D array
print(np.dot(b, a), '\n')                      # a (1D array) is treated as column vector # gives 1D array
print(np.dot(np.array(a), np.array(b)),'\n' )  # a (1D array) is treated as row vector # gives 1D array
print(np.dot(np.array(b), np.array(a)))        # a (1D array) is treated as column vector # gives 1D array

[[4, 1], [2, 2]] 

[[4 1]
 [2 2]] 

[6 3] 

[5 4] 

[6 3] 

[5 4]


In [210]:
#help(np.dot)

a = [[1, 1]]            # 2D
e = [[1], [1]]          # 2D
b = [[4, 1], [2, 2]]    # 2D


print(a, '\n')            # 2D
print(np.array(e), '\n')  # 2D

#  matrix product between 1D and 2D array
print(np.dot(a, b), '\n')                      # gives 2D array
print(np.dot(b, e), '\n')                      # gives 2D array
print(np.dot(np.array(a), np.array(b)),'\n' )  # gives 2D array
print(np.dot(np.array(b), np.array(e)))        # gives 2D array

[[1, 1]] 

[[1]
 [1]] 

[[6 3]] 

[[5]
 [4]] 

[[6 3]] 

[[5]
 [4]]


In [71]:
a = np.array([1+2j,3+4j])
b = np.array([5+6j,7+8j])
print(np.dot(a, b))        #  Dot product of two 1D complex arrays (vectors). Returns complex scallar.

(-18+68j)


In [105]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]

print(np.dot(a, b), '\n')                      # matrix multiplication
print(np.dot(np.array(a), np.array(b)), '\n')  # matrix multiplication
print(np.array(a)@np.array(b))   # for 2D-arrays @ or matmul is preferred as matrix multiplication occurs

[[4 1]
 [2 2]] 

[[4 1]
 [2 2]] 

[[4 1]
 [2 2]]


In [182]:
a = np.array([[1+2j, 2+3j], [2+3j, 1+2j]])
b = np.array([[4+3j, 1+2j], [2+3j, 2+3j]])

print(np.dot(a, b), '\n') # it is just matrix multiplication.
print(a@b)

[[-7.+23.j -8.+16.j]
 [-5.+25.j -8.+14.j]] 

[[-7.+23.j -8.+16.j]
 [-5.+25.j -8.+14.j]]


In [69]:
a = 5                    # 0D i.e., scalar
b = [[4, 1], [2, 2]]

print(np.dot(a, b), '\n')                      # simple scalar product
print(np.dot(np.array(a), np.array(b)), '\n')  # simple scalar product
print(np.array(a)*np.array(b), '\n')
print(np.multiply(a,b), '\n')                  # * or multiply() is preferred as simple scalar product occurs
print(np.multiply(np.array(a), np.array(b)), '\n') 

[[20  5]
 [10 10]] 

[[20  5]
 [10 10]] 

[[20  5]
 [10 10]] 

[[20  5]
 [10 10]] 

[[20  5]
 [10 10]] 



`linalg.multi_dot()` : 

In [243]:
#help(la.multi_dot)

a = np.array([1, 1])              # 1D array will be treated as row vector
b = np.array([[4, 1], [2, 2]])    # 2D array
c = np.array([[1, 3], [1, 4]])    # 2D array
d = np.array([5, 1])              # 1D array will be treated as column vector

print(np.dot(np.dot(np.dot(a, b), c), d)) # this can be replaced by below
print(la.multi_dot([a, b, c, d]))       # dot prodict. last argument (d) will be considered as column vector 

75
75


In [244]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
c = np.array([[1, 3], [1, 4]])
d = np.array([[5, 7], [3, 1]])

print(np.dot(np.dot(np.dot(a, b), c), d)) # this can be replaced by below
print(la.multi_dot([b, c]))         # matrix mutiplication of more than two matrices at a time

[[73 51]
 [62 42]]
[[ 5 16]
 [ 4 14]]


`vdot()` : Return the dot product of two vectors, whatever the dimensions of the arrays be. If arguments are mutidimensional arrays then they are first converted into vectors by flattening them into 1D arrays and then dot product occurs. Consequently, `vdot()` should only be used for vectors.

In [74]:
a = [1, 0, 0, 1]
b = [4, 1, 2, 2]

print(np.vdot(a, b)) 

6


In [86]:
a = np.array([1, 0, 0, 1])
b = np.array([4, 1, 2, 2])

print(np.vdot(a, b)) 

6


In [214]:
#help(np.vdot)
a = np.array([1+2j, 3+4j])
b = np.array([5+6j, 7+8j])

print(np.vdot(a, b))      # Complex conjugate of the first argument (a) is considered for the dot product.

(70-8j)


In [215]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
print(np.vdot(a, b))   # dot product between flattened a and b i.e., 1D of a and b. No matrix multiplication.

6


In [111]:
a = np.array([1, 0, 0, 1])
b = np.array([[4, 1], [2, 2]])

print(np.vdot(a, b), '\n')   # np.dot(a, b) not possible.

6 



In [81]:
a = np.array([[1+2j, 2+3j], [2+3j, 1+2j]])
b = np.array([[4+3j, 1+2j], [2+3j, 2+3j]])
print(np.vdot(a, b))   # dot product between complex conjugate of flattened a and flattened b.

(39-5j)


`inner()` : Ordinary inner product of vectors for 1-D arrays (without complex conjugation), in higher dimensions a sum product over the last axes. If any of the array is multidimensional array (dim > 2) `out.shape = (*a.shape[:-1], *b.shape[:-1])`.

In [84]:
#help(np.inner)

a = [1, 0, 0, 1]
b = [4, 1, 2, 2]

print(np.inner(a, b)) 

6


In [90]:
#help(np.inner)

a = np.array([1, 0, 0, 1])
b = np.array([4, 1, 2, 2])

print(np.inner(a, b))  # for 1D arrays this is basically sum(a[:]*b[:]).
print(sum(a[:]*b[:]))

6
6


In [93]:
a = np.array([1+2j,3+4j])
b = np.array([5+6j,7+8j])

print(np.inner(a, b)) # dot product between two complex vectors (1D arrays) without taking complex conjugate like in np.dot()
print(np.dot(a, b))

(-18+68j)
(-18+68j)


In [103]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
print(np.inner(a, b))

[[4 2]
 [1 2]]


In [216]:
a = np.array([[1, 2], [3, 1]])
b = np.array([[4, 1], [2, 2]])
print(np.inner(a, b))

[[ 6  6]
 [13  8]]


In [116]:
a = np.array([1, 0, 0, 1])
b = np.array([[4, 1], [2, 2]])
c=5

print(np.inner(c, b), '\n') # scalar multiplication
print(np.inner(c, a), '\n')
#print(np.inner(a, b), '\n')

[[20  5]
 [10 10]] 

[5 0 0 5] 



In [137]:
a = np.eye(2, 2)

print(5*a)

[[5. 0.]
 [0. 5.]]


In [130]:
a = np.array([1, 1])
b = np.array([[4, 1], [2, 2]])

print(np.inner(a, b), '\n')
print(np.dot(a, b.T), '\n')
print(np.inner(b, a), '\n')
print(np.inner(a, b).shape, '\n')
print(np.inner(b, a).shape, '\n')

[5 4] 

[5 4] 

[5 4] 

(2,) 

(2,) 



In [132]:
a = np.arange(24).reshape((2,3,4))
b = np.arange(4)

print(np.inner(a, b), '\n')
print(np.dot(a, b.T), '\n')
print(np.inner(b, a), '\n')
print(np.inner(a, b).shape, '\n')
print(np.inner(b, a).shape, '\n')

[[ 14  38  62]
 [ 86 110 134]] 

[[ 14  38  62]
 [ 86 110 134]] 

[[ 14  38  62]
 [ 86 110 134]] 

(2, 3) 

(2, 3) 



In [258]:
a = np.arange(2).reshape((1,1,2))
b = np.arange(6).reshape((3,2))

print(np.inner(a, b))
print(np.inner(a, b).shape)
#print((a.shape[:-1], b.shape[:-1]))

[[[1 3 5]]]
(1, 1, 3)


In [118]:
a = np.array([[1+2j, 2+3j], [2+3j, 1+2j]])
b = np.array([[4+3j, 1+2j], [2+3j, 2+3j]])

print(np.inner(a, b), '\n') # this is not matrix multiplication between a and b rather in between a and b.T.
print(np.dot(a, b.T), '\n')
print(np.dot(a, b), '\n')
print(a@b, '\n')

[[-6.+18.j -9.+19.j]
 [-4.+22.j -9.+19.j]] 

[[-6.+18.j -9.+19.j]
 [-4.+22.j -9.+19.j]] 

[[-7.+23.j -8.+16.j]
 [-5.+25.j -8.+14.j]] 

[[-7.+23.j -8.+16.j]
 [-5.+25.j -8.+14.j]] 



In [118]:
a = np.array([[1+2j, 2+3j], [2+3j, 1+2j]])
b = np.array([[4+3j, 1+2j], [2+3j, 2+3j]])

print(np.inner(a, b), '\n') # this is not matrix multiplication between a and b rather in between a and b.T.
print(np.dot(a, b.T), '\n')
print(np.dot(a, b), '\n')
print(a@b, '\n')

[[-6.+18.j -9.+19.j]
 [-4.+22.j -9.+19.j]] 

[[-6.+18.j -9.+19.j]
 [-4.+22.j -9.+19.j]] 

[[-7.+23.j -8.+16.j]
 [-5.+25.j -8.+14.j]] 

[[-7.+23.j -8.+16.j]
 [-5.+25.j -8.+14.j]] 



In [133]:
a = np.array([1+2j, 2+3j])
b = np.array([[4+3j, 1+2j], [2+3j, 2+3j]])

print(np.inner(a, b), '\n') # this is not matrix multiplication between a and b rather in between a and b.T.
print(np.dot(a, b.T), '\n')
print(np.dot(a, b), '\n')
print(a@b, '\n')

print(np.inner(a, b).shape, '\n')
print(np.inner(b, a).shape, '\n')

[-6.+18.j -9.+19.j] 

[-6.+18.j -9.+19.j] 

[-7.+23.j -8.+16.j] 

[-7.+23.j -8.+16.j] 

(2,) 

(2,) 



`outer()`:

In [221]:
#help(np.outer)
a = [1, 0, 0, 1]
b = [4, 1, 2, 2]

print(np.outer(a, b)) 

[[4 1 2 2]
 [0 0 0 0]
 [0 0 0 0]
 [4 1 2 2]]


In [225]:
a = np.array([1, 0, 0, 1])
b = np.array([4, 1, 2, 2])

print(np.outer(b, a))

[[4 0 0 4]
 [1 0 0 1]
 [2 0 0 2]
 [2 0 0 2]]


In [233]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])

print(np.outer(a, b))            # a and b flattened and then outer product
print(np.outer(b, a))

[[4 1 2 2]
 [0 0 0 0]
 [0 0 0 0]
 [4 1 2 2]]
[[4 0 0 4]
 [1 0 0 1]
 [2 0 0 2]
 [2 0 0 2]]


In [228]:
a = np.array([1,1])
b = np.array([5+6j,7+8j])

print(np.outer(a, b), '\n')
print(np.outer(b, a))

[[5.+6.j 7.+8.j]
 [5.+6.j 7.+8.j]] 

[[5.+6.j 5.+6.j]
 [7.+8.j 7.+8.j]]


`matmul()`: matrix multiplication

In [259]:
#help(np.matmul)

a = np.array([[1, 2], [3, 1]])
b = np.array([[4, 1], [2, 2]])

print(np.matmul(a, b))
print(a@b)

[[ 8  5]
 [14  5]]
[[ 8  5]
 [14  5]]


`tensordot()`:

In [248]:
#help(np.tensordot)

`einsum()`:

In [250]:
#help(np.einsum)

`linalg.matrix_power()`:

In [255]:
i = np.array([[0, 1], [-1, 0]])

print(la.matrix_power(i, 3), '\n')
print(la.multi_dot([i, i, i]))

[[ 0 -1]
 [ 1  0]] 

[[ 0 -1]
 [ 1  0]]


## Decompositions

## Matrix eigenvalues

`la.eig` : Compute the eigenvalues and right eigenvectors of a square array.

In [148]:
#help(la.eig)

a = np.diag((1, 2, 3))
print(a, '\n')

eigenvalue, eigenvector = la.eig(a)

print(eigenvalue, '\n')
print(eigenvector, '\n')

[[1 0 0]
 [0 2 0]
 [0 0 3]] 

[1. 2. 3.] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



In [152]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a, '\n')

eigenvalue, eigenvector = la.eig(a)

print(eigenvalue, '\n')
print(eigenvector, '\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15] 

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]] 



In [153]:
a = np.array([[2, 1], [1, 2]])
print(a, '\n')

eigenvalue, eigenvector = la.eig(a)

print(eigenvalue, '\n')
print(eigenvector, '\n')

[[2 1]
 [1 2]] 

[3. 1.] 

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]] 



In [157]:
#help(la.eigvals)



In [155]:
a = np.array([[2, 1], [1, 2]])
print(a, '\n')

eigenvalue = la.eigvals(a)

print(eigenvalue, '\n')

[[2 1]
 [1 2]] 

[3. 1.] 



## Norms and other numbers

## Solving equations and inverting matrices

## Exceptions

## Linear algebra on several matrices at once