In [57]:
import numpy as np
from random import *

In [53]:
def Cnm(n,m):
    Θ = m*(360/n)*(np.pi/180)
    Cnm = np.round(np.array([[np.cos(Θ), -np.sin(Θ), 0],
                   [np.sin(Θ), np.cos(Θ), 0],
                   [0, 0, 1]]), 3)
    return Cnm

In [55]:
print(Cnm(3,1))

[[-0.5   -0.866  0.   ]
 [ 0.866 -0.5    0.   ]
 [ 0.     0.     1.   ]]


In [73]:
coordinates = [tuple([randint(1, 10) for _ in range(3)]) for _ in range(5)]

In [78]:
np.array(coordinates).T

array([[ 1,  8,  1,  4,  6],
       [ 2,  5, 10,  8,  7],
       [ 8, 10,  3,  5,  1]])

In [75]:
print(coordinates)

[(1, 2, 8), (8, 5, 10), (1, 10, 3), (4, 8, 5), (6, 7, 1)]


In [79]:
Cnm(3,1)@np.array(coordinates).T

array([[-2.232, -8.33 , -9.16 , -8.928, -9.062],
       [-0.134,  4.428, -4.134, -0.536,  1.696],
       [ 8.   , 10.   ,  3.   ,  5.   ,  1.   ]])

In [80]:
np.dot(Cnm(3,1),np.array(coordinates).T)

array([[-2.232, -8.33 , -9.16 , -8.928, -9.062],
       [-0.134,  4.428, -4.134, -0.536,  1.696],
       [ 8.   , 10.   ,  3.   ,  5.   ,  1.   ]])

In [95]:
coor = [[1,1,1],[1,2,3],[2,2,2],[3,6,9]]

In [97]:
print(np.array(coor).T)
print(smp.Matrix(np.array(coor).T).rref())

[[1 1 2 3]
 [1 2 2 6]
 [1 3 2 9]]
(Matrix([
[1, 0, 2, 0],
[0, 1, 0, 3],
[0, 0, 0, 0]]), (0, 1))


In [86]:
import sympy as smp